# Generated by Django 6.0.4 on 2026-04-29 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_student_grade_student_parent_contact_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_ride', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
            ],
        ),
    ]
